export interface Phrase {
  text: string;
  /** Optional subtitle or context line */
  sub?: string;
}

export const phrases: Phrase[] = [
  { text: "нет" },
  { text: "ноу" },
  { text: "не" },
  { text: "точно нет" },
  { text: "никогда нет" },
  { text: "ну нет" },
  { text: "не-а" },
  { text: "ни за что" },
  { text: "никак нет" },
  { text: "отбой" },
  { text: "не надо" },
  { text: "не получится" },
  { text: "забудь" },
  { text: "мимо" },
  { text: "nope" },
  { text: "nah" },
  { text: "no" },
  { text: "NO" },
  { text: "НЕТ" },
  { text: "не при каких", sub: "обстоятельствах" },
  { text: "даже не спрашивай" },
  { text: "и не подумаю" },
  { text: "ни в жизнь" },
  { text: "ни за какие", sub: "коврижки" },
  { text: "не сегодня" },
  { text: "не завтра" },
  { text: "не когда-либо" },
  { text: "отрицательно", sub: "ответ: нет" },
  { text: "не одобрено" },
  { text: "запрещено" },
  { text: "нельзя" },
  { text: "неa" },
  { text: "неееет" },
  { text: "не-не-не" },
  { text: "не бывает" },
  { text: "не выйдет" },
  { text: "не судьба" },
  { text: "не в этой", sub: "вселенной" },
  { text: "не в этой жизни" },
  { text: "ни при каких условиях" },
  { text: "категорически нет" },
  { text: "абсолютно нет" },
  { text: "100% нет" },
  { text: "0% да", sub: "остальное — нет" },
  { text: "false" },
  { text: "negative" },
  { text: "declined" },
  { text: "rejected" },
  { text: "denied" },
  { text: "negatory" },
  { text: "не думай" },
  { text: "не мечтай" },

  { text: "не тянет" },
  { text: "не канает" },
  { text: "не катит" },
  { text: "не прокатит" },
  { text: "не пройдёт" },
  { text: "не сработает" },
  { text: "не вариант" },
  { text: "не вариант вообще" },
  { text: "не интересует" },
  { text: "не актуально" },
  { text: "не релевантно" },
  { text: "не подходит" },
  { text: "не моё" },
  { text: "не твоё" },
  { text: "не наше" },
  { text: "не сейчас" },
  { text: "не потом" },
  { text: "не никогда" },
  { text: "ни-ни" },
  { text: "ни в коем случае" },
  { text: "ни за что на свете" },
  { text: "ни за миллион" },
  { text: "ни за миллиард" },
  { text: "ни за что не" },
  { text: "🙅" },
  { text: "🚫" },
  { text: "⛔" },
  { text: "❌" },
  { text: "👎" },
  { text: "🤚", sub: "стоп" },
  { text: "✋", sub: "стоп" },
  { text: "🛑" },
  { text: "не сейчас, спасибо" },
  { text: "может быть... нет" },
  { text: "да? нет." },
  { text: "да нет же" },
  { text: "да ну" },
  { text: "да ладно, нет" },
  { text: "конечно нет" },
  { text: "разумеется нет" },
  { text: "естественно нет" },
  { text: "очевидно нет" },
  { text: "безусловно нет" },
  { text: "однозначно нет" },
  { text: "несомненно нет" },
  { text: "бесспорно нет" },
  { text: "непременно нет" },
  { text: "неизбежно нет" },
  { text: "фатально нет" },
  { text: "смертельно нет" },
  { text: "окончательно нет" },
  { text: "финальный ответ: нет" },
  { text: "последнее слово: нет" },
  { text: "точка", sub: "нет" },
  { text: "конец", sub: "нет" },
  { text: "стоп" },
  { text: "halt" },
  { text: "stop" },
  { text: "cease" },
  { text: "desist" },
  { text: "abstain" },
  { text: "refuse" },
  { text: "reject" },
  { text: "decline" },
  { text: "deny" },
  { text: "veto" },
  { text: "vetoed" },
  { text: "blocked" },
  { text: "forbidden" },
  { text: "prohibited" },
  { text: "banned" },
  { text: "blacklisted" },
  { text: "whitelisted: нет" },
  { text: "null" },
  { text: "undefined" },
  { text: "NaN" },
  { text: "0", sub: "это нет" },
  { text: "falsey" },
  { text: "falsy" },
  { text: "truthy: нет" },
  { text: "boolean: false" },
  { text: "return false" },
  { text: "throw new Error('нет')" },
  { text: "console.log('нет')" },
  { text: "alert('нет')" },
  { text: "404", sub: "not found: да" },
  { text: "403", sub: "forbidden: да" },
  { text: "500", sub: "internal no error" },
  { text: "502", sub: "bad gateway to yes" },
  { text: "503", sub: "service unavailable: да" },
  { text: "418", sub: "i'm a teapot, not a yes" },
];

export function pickPhrase(): Phrase {
  return phrases[Math.floor(Math.random() * phrases.length)];
}
