import type { Phrase } from "./phrase";

export const phrasesEn: Phrase[] = [
  { text: "no" },
  { text: "nope" },
  { text: "nah" },
  { text: "definitely no" },
  { text: "never no" },
  { text: "well, no" },
  { text: "nuh-uh" },
  { text: "no way" },
  { text: "negative" },
  { text: "n" },
  { text: "nop" },
  { text: "forget it" },
  { text: "miss" },
  { text: "nope" },
  { text: "nah" },
  { text: "no" },
  { text: "NO" },
  { text: "NOPE" },
  { text: "under no", sub: "circumstances" },
  { text: "don't even ask" },
  { text: "not a chance" },
  { text: "not in this lifetime" },
  { text: "not for all the", sub: "tea in China" },
  { text: "not today" },
  { text: "not tomorrow" },
  { text: "not ever" },
  { text: "negative" },
  { text: "nah-uh" },
  { text: "no no no no" },
  { text: "not in this universe" },
  { text: "not in this reality" },
  { text: "n" },
  { text: "nooo" },
  { text: "noooooo" },
  { text: "no-no-no" },
  { text: "never happens" },
  { text: "won't work" },
  { text: "not meant to be" },
  { text: "not in this", sub: "universe" },
  { text: "not in this life" },
  { text: "under no conditions" },
  { text: "categorically no" },
  { text: "absolutely no" },
  { text: "100% no" },
  { text: "0% yes", sub: "the rest is no" },
  { text: "false" },
  { text: "negative" },
  { text: "not cutting it" },
  { text: "not happening" },
  { text: "not flying" },
  { text: "won't fly" },
  { text: "won't pass" },
  { text: "won't work" },
  { text: "not an option" },
  { text: "not an option at all" },
  { text: "not interested" },
  { text: "not relevant" },
  { text: "not applicable" },
  { text: "doesn't fit" },
  { text: "not my thing" },
  { text: "not your thing" },
  { text: "not our thing" },
  { text: "not now" },
  { text: "not later" },
  { text: "not never" },
  { text: "nope-nope" },
  { text: "in no case" },
  { text: "not for anything in the world" },
  { text: "not for a million" },
  { text: "not for a billion" },
  { text: "no way ever" },
  { text: "🙅" },
  { text: "🚫" },
  { text: "⛔" },
  { text: "❌" },
  { text: "👎" },
  { text: "not right now, thanks" },
  { text: "maybe... no" },
  { text: "yeah no" },
  { text: "yeah, no though" },
  { text: "yeah right" },
  { text: "sure, no" },
  { text: "of course not" },
  { text: "obviously not" },
  { text: "naturally not" },
  { text: "clearly no" },
  { text: "absolutely not" },
  { text: "unquestionably no" },
  { text: "undoubtedly no" },
  { text: "indisputably no" },
  { text: "certainly no" },
  { text: "inevitably no" },
  { text: "fatally no" },
  { text: "mortally no" },
  { text: "definitively no" },
  { text: "final answer: no" },
  { text: "last word: no" },
  { text: "null" },
  { text: "NaN" },
  { text: "0", sub: "that's not a one" },
  { text: "return false" },

  // Polite
  { text: "no, thank you" },
  { text: "thanks, but no" },
  { text: "I appreciate it,", sub: "but no" },
  { text: "kind offer,", sub: "hard pass" },
  { text: "that's sweet,", sub: "still no" },
  { text: "bold of you to ask" },
  { text: "nice try though" },
  { text: "A for effort,", sub: "F for outcome" },
  { text: "let me think...", sub: "(thought about it — no)" },
  { text: "spoiler: no" },
  { text: "I'll pass" },
  { text: "I'll sit this one out" },
  { text: "not for me" },
  { text: "not my thing" },
  { text: "I'd rather not" },
  { text: "I think I'm good" },
  { text: "I'm going to have", sub: "to say no" },
  { text: "respectfully, no" },
  { text: "with all due respect,", sub: "no" },
  { text: "I wish I could say yes", sub: "I can't" },
  { text: "as much as I'd love to", sub: "no" },
  { text: "tempting,", sub: "but no" },
  { text: "interesting proposal,", sub: "no" },
  { text: "I'll have to decline" },
  { text: "regretfully, no" },
  { text: "unfortunately, no" },
  { text: "sadly, no" },
  { text: "tragically, no" },
  { text: "devastatingly, no" },
  { text: "my sincerest no" },
  { text: "no, with love" },
  { text: "no, with respect" },
  { text: "no, warmly" },
  { text: "no, fondly" },
  { text: "a warm no" },
  { text: "a firm but gentle no" },
  { text: "a heartfelt no" },
  { text: "I've considered it", sub: "no" },
  { text: "after careful thought,", sub: "no" },
  { text: "upon reflection,", sub: "still no" },
  { text: "I've slept on it", sub: "no" },
  { text: "the answer remains no" },
  { text: "my final answer is no" },
  { text: "and the verdict is:", sub: "no" },
  { text: "the committee has voted:", sub: "no" },
  { text: "HR has been consulted:", sub: "no" },
  { text: "management says no" },
  { text: "the universe says no" },
  { text: "the stars aren't aligned" },
  { text: "Mercury is in retrograde", sub: "so, no" },
  { text: "per my last email,", sub: "no" },
  { text: "as previously stated,", sub: "no" },
  { text: "please see attached:", sub: "no" },
  { text: "per our conversation,", sub: "no" },
  { text: "circling back to say:", sub: "no" },
  { text: "just following up —", sub: "still no" },
  { text: "touching base:", sub: "no" },
];
