export interface Phrase {
  text: string;
  /** Optional subtitle or context line */
  sub?: string;
  /** How to display: shout, whisper, question, etc. */
  mood?: "hard" | "soft" | "playful" | "formal" | "dramatic";
}

export const phrases: Phrase[] = [
  { text: "нет", mood: "hard" },
  { text: "ноу", mood: "playful" },
  { text: "не", mood: "soft" },
  { text: "отказать", mood: "formal" },
  { text: "точно нет", mood: "hard" },
  { text: "никогда нет", mood: "dramatic" },
  { text: "ну нет", mood: "playful" },
  { text: "не-а", mood: "playful" },
  { text: "ни за что", mood: "hard" },
  { text: "никак нет", mood: "formal" },
  { text: "отбой", mood: "hard" },
  { text: "отказ", mood: "formal", sub: "№ 404" },
  { text: "не надо", mood: "soft" },
  { text: "не получится", mood: "soft" },
  { text: "забудь", mood: "dramatic" },
  { text: "мимо", mood: "playful" },
  { text: "nope", mood: "playful" },
  { text: "nah", mood: "playful" },
  { text: "no", mood: "hard" },
  { text: "NO", mood: "dramatic" },
  { text: "НЕТ", mood: "dramatic" },
  { text: "не при каких", mood: "formal", sub: "обстоятельствах" },
  { text: "даже не спрашивай", mood: "dramatic" },
  { text: "и не подумаю", mood: "playful" },
  { text: "ни в жизнь", mood: "dramatic" },
  { text: "ни за какие", mood: "formal", sub: "коврижки" },
  { text: "не сегодня", mood: "soft" },
  { text: "не завтра", mood: "soft" },
  { text: "не когда-либо", mood: "formal" },
  { text: "отрицательно", mood: "formal", sub: "ответ: нет" },
  { text: "отклонено", mood: "formal" },
  { text: "отвергнуто", mood: "formal" },
  { text: "не одобрено", mood: "formal" },
  { text: "в доступе отказано", mood: "formal" },
  { text: "запрещено", mood: "hard" },
  { text: "нельзя", mood: "soft" },
  { text: "неa", mood: "playful" },
  { text: "неееет", mood: "playful" },
  { text: "не-не-не", mood: "playful" },
  { text: "не бывает", mood: "soft" },
  { text: "не выйдет", mood: "soft" },
  { text: "не судьба", mood: "dramatic" },
  { text: "не в этой", mood: "dramatic", sub: "вселенной" },
  { text: "не в этой жизни", mood: "dramatic" },
  { text: "ни при каких условиях", mood: "formal" },
  { text: "категорически нет", mood: "formal" },
  { text: "абсолютно нет", mood: "hard" },
  { text: "100% нет", mood: "playful" },
  { text: "0% да", mood: "playful", sub: "остальное — нет" },
  { text: "false", mood: "formal" },
  { text: "negative", mood: "formal" },
  { text: "declined", mood: "formal" },
  { text: "rejected", mood: "formal" },
  { text: "denied", mood: "formal" },
  { text: "negatory", mood: "formal" },
  { text: "не думай", mood: "soft" },
  { text: "не мечтай", mood: "dramatic" },
  { text: "не жди", mood: "dramatic" },
  { text: "не верь", mood: "dramatic" },
  { text: "не тянет", mood: "playful" },
  { text: "не канает", mood: "playful" },
  { text: "не катит", mood: "playful" },
  { text: "не прокатит", mood: "playful" },
  { text: "не пройдёт", mood: "soft" },
  { text: "не сработает", mood: "soft" },
  { text: "не вариант", mood: "playful" },
  { text: "не вариант вообще", mood: "hard" },
  { text: "не согласен", mood: "formal" },
  { text: "не согласна", mood: "formal" },
  { text: "не согласны", mood: "formal" },
  { text: "не интересует", mood: "formal" },
  { text: "не актуально", mood: "formal" },
  { text: "не релевантно", mood: "formal" },
  { text: "не подходит", mood: "soft" },
  { text: "не моё", mood: "soft" },
  { text: "не твоё", mood: "soft" },
  { text: "не наше", mood: "soft" },
  { text: "не сейчас", mood: "soft" },
  { text: "не потом", mood: "soft" },
  { text: "не никогда", mood: "dramatic" },
  { text: "ни-ни", mood: "playful" },
  { text: "ни в коем случае", mood: "formal" },
  { text: "ни за что на свете", mood: "dramatic" },
  { text: "ни за миллион", mood: "dramatic" },
  { text: "ни за миллиард", mood: "dramatic" },
  { text: "ни за что не", mood: "hard" },
  { text: "отказано", mood: "formal" },
  { text: "отказано в доступе", mood: "formal" },
  { text: "отказано системой", mood: "formal" },
  { text: "отказано судьбой", mood: "dramatic" },
  { text: "отказано вселенной", mood: "dramatic" },
  { text: "отказано логикой", mood: "formal" },
  { text: "отказано здравым смыслом", mood: "formal" },
  { text: "отказано интуицией", mood: "soft" },
  { text: "отказано сердцем", mood: "dramatic" },
  { text: "отказано разумом", mood: "formal" },
  { text: "отказано совестью", mood: "formal" },
  { text: "отказано принципами", mood: "formal" },
  { text: "отказано правилами", mood: "formal" },
  { text: "отказано законом", mood: "formal" },
  { text: "отказано начальством", mood: "formal" },
  { text: "отказано мамой", mood: "playful" },
  { text: "отказано папой", mood: "playful" },
  { text: "отказано бабушкой", mood: "playful" },
  { text: "отказано дедушкой", mood: "playful" },
  { text: "отказано котом", mood: "playful" },
  { text: "отказано собакой", mood: "playful" },
  { text: "отказано рыбкой", mood: "playful" },
  { text: "отказано растением", mood: "playful" },
  { text: "отказано камнем", mood: "playful" },
  { text: "отказано облаком", mood: "playful" },
  { text: "отказано звёздами", mood: "dramatic" },
  { text: "отказано луной", mood: "dramatic" },
  { text: "отказано солнцем", mood: "dramatic" },
  { text: "отказано дождём", mood: "dramatic" },
  { text: "отказано ветром", mood: "dramatic" },
  { text: "отказано снегом", mood: "dramatic" },
  { text: "отказано временем", mood: "dramatic" },
  { text: "отказано пространством", mood: "dramatic" },
  { text: "отказано измерением", mood: "formal" },
  { text: "отказано матрицей", mood: "formal" },
  { text: "отказано алгоритмом", mood: "formal" },
  { text: "отказано нейросетью", mood: "formal" },
  { text: "отказано ИИ", mood: "formal" },
  { text: "отказано ботом", mood: "formal" },
  { text: "отказано скриптом", mood: "formal" },
  { text: "отказано кодом", mood: "formal" },
  { text: "отказано багом", mood: "playful" },
  { text: "отказано фичей", mood: "playful" },
  { text: "отказано релизом", mood: "playful" },
  { text: "отказано деплоем", mood: "playful" },
  { text: "отказано продакшеном", mood: "playful" },
  { text: "отказано стейджингом", mood: "playful" },
  { text: "отказано девом", mood: "playful" },
  { text: "отказано локалхостом", mood: "playful" },
  { text: "отказано 127.0.0.1", mood: "playful" },
  { text: "отказано DNS", mood: "formal" },
  { text: "отказано HTTP 403", mood: "formal" },
  { text: "отказано HTTP 404", mood: "formal" },
  { text: "отказано HTTP 500", mood: "formal" },
  { text: "отказано CORS", mood: "formal" },
  { text: "отказано CSP", mood: "formal" },
  { text: "отказано GDPR", mood: "formal" },
  { text: "отказано Terms of Service", mood: "formal" },
  { text: "отказано Privacy Policy", mood: "formal" },
  { text: "отказано лицензией", mood: "formal" },
  { text: "отказано патентом", mood: "formal" },
  { text: "отказано авторским правом", mood: "formal" },
  { text: "отказано NDA", mood: "formal" },
  { text: "отказано SLA", mood: "formal" },
  { text: "отказано KPI", mood: "formal" },
  { text: "отказано OKR", mood: "formal" },
  { text: "отказано roadmap", mood: "formal" },
  { text: "отказано backlog", mood: "formal" },
  { text: "отказано sprint", mood: "formal" },
  { text: "отказано retro", mood: "formal" },
  { text: "отказано standup", mood: "formal" },
  { text: "отказано meeting", mood: "formal" },
  { text: "отказано email", mood: "formal" },
  { text: "отказано Slack", mood: "formal" },
  { text: "отказано Teams", mood: "formal" },
  { text: "отказано Zoom", mood: "formal" },
  { text: "отказано календарём", mood: "formal" },
  { text: "отказано дедлайном", mood: "formal" },
  { text: "отказано бюджетом", mood: "formal" },
  { text: "отказано инвестором", mood: "formal" },
  { text: "отказано рынком", mood: "formal" },
  { text: "отказано конкурентом", mood: "formal" },
  { text: "отказано клиентом", mood: "formal" },
  { text: "отказано пользователем", mood: "formal" },
  { text: "отказано модератором", mood: "formal" },
  { text: "отказано алгоритмом ленты", mood: "formal" },
  { text: "отказано рекомендациями", mood: "formal" },
  { text: "отказано трендами", mood: "formal" },
  { text: "отказано хайпом", mood: "playful" },
  { text: "отказано мемам", mood: "playful" },
  { text: "отказано TikTok", mood: "playful" },
  { text: "отказано Instagram", mood: "playful" },
  { text: "отказано Twitter", mood: "playful" },
  { text: "отказано Reddit", mood: "playful" },
  { text: "отказано Hacker News", mood: "playful" },
  { text: "отказано Product Hunt", mood: "playful" },
  { text: "отказано GitHub", mood: "playful" },
  { text: "отказано GitLab", mood: "playful" },
  { text: "отказано Bitbucket", mood: "playful" },
  { text: "отказано npm", mood: "playful" },
  { text: "отказано yarn", mood: "playful" },
  { text: "отказано pnpm", mood: "playful" },
  { text: "отказано bun", mood: "playful" },
  { text: "отказано deno", mood: "playful" },
  { text: "отказано node", mood: "playful" },
  { text: "отказано python", mood: "playful" },
  { text: "отказано rust", mood: "playful" },
  { text: "отказано go", mood: "playful" },
  { text: "отказано java", mood: "playful" },
  { text: "отказано c++", mood: "playful" },
  { text: "отказано assembly", mood: "playful" },
  { text: "отказано binary", mood: "playful" },
  { text: "отказано hex", mood: "playful" },
  { text: "отказано unicode", mood: "playful" },
  { text: "отказано emoji", mood: "playful" },
  { text: "отказано 🚫", mood: "playful", sub: "⛔ ❌ 🙅" },
  { text: "🙅", mood: "playful" },
  { text: "🚫", mood: "playful" },
  { text: "⛔", mood: "playful" },
  { text: "❌", mood: "playful" },
  { text: "👎", mood: "playful" },
  { text: "🤚", mood: "playful", sub: "стоп" },
  { text: "✋", mood: "playful", sub: "стоп" },
  { text: "🛑", mood: "playful" },
  { text: "не сейчас, спасибо", mood: "soft" },
  { text: "может быть... нет", mood: "playful" },
  { text: "да? нет.", mood: "playful" },
  { text: "да нет же", mood: "playful" },
  { text: "да ну", mood: "playful" },
  { text: "да ладно, нет", mood: "playful" },
  { text: "конечно нет", mood: "hard" },
  { text: "разумеется нет", mood: "formal" },
  { text: "естественно нет", mood: "formal" },
  { text: "очевидно нет", mood: "formal" },
  { text: "безусловно нет", mood: "formal" },
  { text: "однозначно нет", mood: "hard" },
  { text: "несомненно нет", mood: "formal" },
  { text: "бесспорно нет", mood: "formal" },
  { text: "непременно нет", mood: "formal" },
  { text: "неизбежно нет", mood: "dramatic" },
  { text: "фатально нет", mood: "dramatic" },
  { text: "смертельно нет", mood: "dramatic" },
  { text: "окончательно нет", mood: "hard" },
  { text: "окончательный отказ", mood: "formal" },
  { text: "финальный ответ: нет", mood: "formal" },
  { text: "последнее слово: нет", mood: "dramatic" },
  { text: "точка", mood: "hard", sub: "нет" },
  { text: "конец", mood: "dramatic", sub: "нет" },
  { text: "стоп", mood: "hard" },
  { text: "halt", mood: "formal" },
  { text: "stop", mood: "hard" },
  { text: "cease", mood: "formal" },
  { text: "desist", mood: "formal" },
  { text: "abstain", mood: "formal" },
  { text: "refuse", mood: "formal" },
  { text: "reject", mood: "formal" },
  { text: "decline", mood: "formal" },
  { text: "deny", mood: "formal" },
  { text: "veto", mood: "formal" },
  { text: "vetoed", mood: "formal" },
  { text: "blocked", mood: "formal" },
  { text: "forbidden", mood: "hard" },
  { text: "prohibited", mood: "formal" },
  { text: "banned", mood: "hard" },
  { text: "blacklisted", mood: "formal" },
  { text: "whitelisted: нет", mood: "playful" },
  { text: "null", mood: "formal" },
  { text: "undefined", mood: "formal" },
  { text: "NaN", mood: "playful" },
  { text: "0", mood: "formal", sub: "это нет" },
  { text: "falsey", mood: "formal" },
  { text: "falsy", mood: "formal" },
  { text: "truthy: нет", mood: "playful" },
  { text: "boolean: false", mood: "formal" },
  { text: "return false", mood: "formal" },
  { text: "throw new Error('нет')", mood: "playful" },
  { text: "console.log('нет')", mood: "playful" },
  { text: "alert('нет')", mood: "playful" },
  { text: "404", mood: "formal", sub: "not found: да" },
  { text: "403", mood: "formal", sub: "forbidden: да" },
  { text: "500", mood: "formal", sub: "internal no error" },
  { text: "502", mood: "formal", sub: "bad gateway to yes" },
  { text: "503", mood: "formal", sub: "service unavailable: да" },
  { text: "418", mood: "playful", sub: "i'm a teapot, not a yes" },
];

export function pickPhrase(): Phrase {
  return phrases[Math.floor(Math.random() * phrases.length)];
}
