import { createDeckPicker } from "./shuffle-pick";

export interface Phrase {
  text: string;
  /** Optional subtitle or context line */
  sub?: string;
}

function phraseKey(phrase: Phrase): string {
  return `${phrase.text}\0${phrase.sub ?? ""}`;
}

export const phrases: Phrase[] = [
  { text: "нет" },
  { text: "ноу" },
  { text: "не" },
  { text: "точно нет" },
  { text: "никогда нет" },
  { text: "ну нет" },
  { text: "не-а" },
  { text: "ни за что" },
  { text: "никак нет" },
  { text: "n" },
  { text: "ноуп" },
  { text: "забудь" },
  { text: "мимо" },
  { text: "nope" },
  { text: "nah" },
  { text: "no" },
  { text: "NO" },
  { text: "НЕТ" },
  { text: "не при каких", sub: "обстоятельствах" },
  { text: "даже не спрашивай" },
  { text: "и не подумаю" },
  { text: "ни в жизнь" },
  { text: "ни за какие", sub: "коврижки" },
  { text: "не сегодня" },
  { text: "не завтра" },
  { text: "не когда-либо" },
  { text: "отрицательно" },
  { text: "не-a" },
  { text: "нет нет нет нет" },
  { text: "не в этой вселенной" },
  { text: "не в этой реальности" },
  { text: "н" },
  { text: "неa" },
  { text: "неееет" },
  { text: "не-не-не" },
  { text: "не бывает" },
  { text: "не выйдет" },
  { text: "не судьба" },
  { text: "не в этой", sub: "вселенной" },
  { text: "не в этой жизни" },
  { text: "ни при каких условиях" },
  { text: "категорически нет" },
  { text: "абсолютно нет" },
  { text: "100% нет" },
  { text: "0% да", sub: "остальное — нет" },
  { text: "false" },
  { text: "negative" },

  { text: "не тянет" },
  { text: "не канает" },
  { text: "не катит" },
  { text: "не прокатит" },
  { text: "не пройдёт" },
  { text: "не сработает" },
  { text: "не вариант" },
  { text: "не вариант вообще" },
  { text: "не интересует" },
  { text: "не актуально" },
  { text: "не релевантно" },
  { text: "не подходит" },
  { text: "не моё" },
  { text: "не твоё" },
  { text: "не наше" },
  { text: "не сейчас" },
  { text: "не потом" },
  { text: "не никогда" },
  { text: "ни-ни" },
  { text: "ни в коем случае" },
  { text: "ни за что на свете" },
  { text: "ни за миллион" },
  { text: "ни за миллиард" },
  { text: "ни за что не" },
  { text: "🙅" },
  { text: "🚫" },
  { text: "⛔" },
  { text: "❌" },
  { text: "👎" },

  { text: "не сейчас, спасибо" },
  { text: "может быть... нет" },
  { text: "да ну нет" },
  { text: "да нет же" },
  { text: "да ну" },
  { text: "да ладно, нет" },
  { text: "конечно нет" },
  { text: "разумеется нет" },
  { text: "естественно нет" },
  { text: "очевидно нет" },
  { text: "безусловно нет" },
  { text: "однозначно нет" },
  { text: "несомненно нет" },
  { text: "бесспорно нет" },
  { text: "непременно нет" },
  { text: "неизбежно нет" },
  { text: "фатально нет" },
  { text: "смертельно нет" },
  { text: "окончательно нет" },
  { text: "финальный ответ: нет" },
  { text: "последнее слово: нет" },

  { text: "null" },
  { text: "NaN" },
  { text: "0", sub: "это ни единички" },
  { text: "return false" },
];

const pickUniquePhrase = createDeckPicker(phrases, phraseKey, "no:phrase-deck");

export function pickPhrase(): Phrase {
  return pickUniquePhrase();
}
