export const refreshLabelsRu: string[] = [
  "А может быть всё-таки да?",
  "Попробуем ещё раз?",
  "Может повезёт?",
  "Может всё же да?",
  "А если ещё разок?",
  "Может на этот раз?",
  "Попробовать снова?",
  "Ещё одна попытка?",
  "Ну может…",
  "Вдруг сейчас да?",
  "А вдруг повезёт?",
  "Может в этот раз?",
  "Ещё разик?",
  "Может передумает?",
  "Давай ещё раз",
  "А ну-ка ещё раз",
  "С этой попытки точно да?",
  "Может на этот раз да?",
  "Ещё кружок?",
  "Снова?",
  "Может сейчас согласится?",
  "А может передумаешь?",
  "Попробуем ещё?",
  "Может всё-таки?",
  "Ещё разочек?",
  "Может повезёт в этот раз?",
  "А вдруг всё-таки да?",
  "Попробуем ещё разок?",
  "Может всё же согласится?",
  "Ещё одна попытка — точно да?",
];

export const refreshLabelsEn: string[] = [
  "Maybe it's yes this time?",
  "Shall we try again?",
  "Maybe we'll get lucky?",
  "Maybe it's yes after all?",
  "One more time?",
  "Maybe this round?",
  "Try again?",
  "Another attempt?",
  "Well, maybe…",
  "What if it's yes now?",
  "Could we get lucky?",
  "Maybe this time?",
  "Once more?",
  "Maybe they'll change their mind?",
  "Let's go again",
  "How about another try?",
  "Surely yes this time?",
  "Maybe yes this round?",
  "Another spin?",
  "Again?",
  "Maybe they'll agree now?",
  "Maybe you'll reconsider?",
  "Shall we try once more?",
  "Maybe after all?",
  "One more go?",
  "Maybe luck's on our side?",
  "What if it's yes after all?",
  "One more try?",
  "Maybe they'll say yes?",
  "Another attempt — surely yes?",
];
